version: '3.8'

services:
    web:
      image: health-app
      build: .
      ports:
          - "5001:5001"
      
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure